-- ==========================================================
-- Hostel Management System - Exact Relational Schema (SQLite)
-- Exactly 18 Tables with Exact Original Attributes
-- ==========================================================

PRAGMA foreign_keys = ON;

-- 1. WARDEN
CREATE TABLE IF NOT EXISTS WARDEN (
    WardenID VARCHAR(10) PRIMARY KEY,
    WardenName VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    JoiningDate VARCHAR(20)
);

-- 2. WARDEN_PHONE
CREATE TABLE IF NOT EXISTS WARDEN_PHONE (
    WardenID VARCHAR(10),
    PhoneNo VARCHAR(20),
    PRIMARY KEY (WardenID, PhoneNo),
    FOREIGN KEY (WardenID) REFERENCES WARDEN(WardenID) ON DELETE CASCADE
);

-- 3. HOSTEL
CREATE TABLE IF NOT EXISTS HOSTEL (
    HostelID VARCHAR(10) PRIMARY KEY,
    HostelName VARCHAR(100) NOT NULL,
    TotalFloors INTEGER,
    WardenID VARCHAR(10),
    FOREIGN KEY (WardenID) REFERENCES WARDEN(WardenID)
);

-- 4. ROOM_TYPE
CREATE TABLE IF NOT EXISTS ROOM_TYPE (
    TypeID VARCHAR(10) PRIMARY KEY,
    TypeName VARCHAR(30),
    AC_Type VARCHAR(20),
    Capacity INTEGER
);

-- 5. ROOM
CREATE TABLE IF NOT EXISTS ROOM (
    RoomNo VARCHAR(10) PRIMARY KEY,
    FloorNo INTEGER,
    Type VARCHAR(30),
    Capacity INTEGER,
    RoomRent NUMERIC,
    HostelID VARCHAR(10),
    FOREIGN KEY (HostelID) REFERENCES HOSTEL(HostelID)
);

-- 6. STUDENT
CREATE TABLE IF NOT EXISTS STUDENT (
    StudentID VARCHAR(10) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Gender VARCHAR(10),
    DOB VARCHAR(20),
    Email VARCHAR(100),
    BloodGroup VARCHAR(5),
    AllergyInfo VARCHAR(100),
    PlanType VARCHAR(50),
    RoomNo VARCHAR(10),
    HostelID VARCHAR(10),
    MessID VARCHAR(10),
    MentorStudentID VARCHAR(10),
    FOREIGN KEY (RoomNo) REFERENCES ROOM(RoomNo),
    FOREIGN KEY (HostelID) REFERENCES HOSTEL(HostelID),
    FOREIGN KEY (MessID) REFERENCES MESS(MessID),
    FOREIGN KEY (MentorStudentID) REFERENCES STUDENT(StudentID)
);

-- 7. STUDENT_PHONE
CREATE TABLE IF NOT EXISTS STUDENT_PHONE (
    StudentID VARCHAR(10),
    PhoneNo VARCHAR(20),
    PRIMARY KEY (StudentID, PhoneNo),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE
);

-- 8. MESS
CREATE TABLE IF NOT EXISTS MESS (
    MessID VARCHAR(10) PRIMARY KEY,
    MessName VARCHAR(100) NOT NULL,
    MessType VARCHAR(30),
    Location VARCHAR(100)
);

-- 9. MESS_CONTACT
CREATE TABLE IF NOT EXISTS MESS_CONTACT (
    MessID VARCHAR(10),
    ContactNo VARCHAR(20),
    PRIMARY KEY (MessID, ContactNo),
    FOREIGN KEY (MessID) REFERENCES MESS(MessID) ON DELETE CASCADE
);

-- 10. MEAL
CREATE TABLE IF NOT EXISTS MEAL (
    MealID VARCHAR(10) PRIMARY KEY,
    MealName VARCHAR(100) NOT NULL,
    Description VARCHAR(200),
    Cost NUMERIC,
    MessID VARCHAR(10),
    FOREIGN KEY (MessID) REFERENCES MESS(MessID) ON DELETE CASCADE
);

-- 11. STAFF
CREATE TABLE IF NOT EXISTS STAFF (
    StaffID VARCHAR(10) PRIMARY KEY,
    StaffName VARCHAR(100) NOT NULL,
    JoinDate VARCHAR(20),
    Salary NUMERIC,
    Role VARCHAR(50),
    MessID VARCHAR(10),
    FOREIGN KEY (MessID) REFERENCES MESS(MessID)
);

-- 12. STAFF_PHONE
CREATE TABLE IF NOT EXISTS STAFF_PHONE (
    StaffID VARCHAR(10),
    PhoneNo VARCHAR(20),
    PRIMARY KEY (StaffID, PhoneNo),
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE
);

-- 13. SUPPLIER
CREATE TABLE IF NOT EXISTS SUPPLIER (
    SupplierID VARCHAR(10) PRIMARY KEY,
    SupplierName VARCHAR(100) NOT NULL
);

-- 14. SUPPLIER_PHONE
CREATE TABLE IF NOT EXISTS SUPPLIER_PHONE (
    SupplierID VARCHAR(10),
    PhoneNo VARCHAR(20),
    PRIMARY KEY (SupplierID, PhoneNo),
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID) ON DELETE CASCADE
);

-- 15. INVENTORY_ITEM
CREATE TABLE IF NOT EXISTS INVENTORY_ITEM (
    ItemID VARCHAR(10) PRIMARY KEY,
    ItemName VARCHAR(100) NOT NULL,
    Category VARCHAR(50),
    Unit VARCHAR(20)
);

-- 16. PROCURES
CREATE TABLE IF NOT EXISTS PROCURES (
    MessID VARCHAR(10),
    SupplierID VARCHAR(10),
    ItemID VARCHAR(10),
    Quantity NUMERIC,
    PRIMARY KEY (MessID, SupplierID, ItemID),
    FOREIGN KEY (MessID) REFERENCES MESS(MessID),
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID),
    FOREIGN KEY (ItemID) REFERENCES INVENTORY_ITEM(ItemID)
);

-- 17. PAYMENT
CREATE TABLE IF NOT EXISTS PAYMENT (
    PaymentID VARCHAR(10) PRIMARY KEY,
    StudentID VARCHAR(10) NOT NULL,
    Amount NUMERIC,
    PaymentMode VARCHAR(30),
    Status VARCHAR(50),
    PaymentDay INTEGER,
    PaymentMonth INTEGER,
    PaymentYear INTEGER,
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);

-- 18. PAYMENT_DETAIL
CREATE TABLE IF NOT EXISTS PAYMENT_DETAIL (
    PaymentID VARCHAR(10),
    DetailID VARCHAR(10),
    Month VARCHAR(30),
    Year INTEGER,
    MessCharges NUMERIC,
    OtherCharges NUMERIC,
    PRIMARY KEY (PaymentID, DetailID),
    FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID) ON DELETE CASCADE
);
